### ISSUE TITLE
UFW missing opened ports

### ISSUE THREAD

**Issue by eduzimrs** [tdewin/veeamhubrepo#3]
Hi Guys,

I may found an issue related to the UFW missing opened ports to data transfer channels (TCP 2500-3300) requested by Veeam in this [page](https://helpcenter.veeam.com/docs/backup/vsphere/used_ports.html?ver=110#linux-server-connections)

I can see the scrip opens the port 6162/tcp which is the Data Mover, i cannot see the others.

When i run the backup job i see the following error:
![photo_2021-07-29_14-52-22](https://user-images.githubusercontent.com/7524875/127541240-6e44fe68-0421-4e38-862b-c92d88163ec8.jpg)

I went through the logs and found the issue, the port 2503 is not open in any UFW rule.
![photo_2021-07-29_14-52-25](https://user-images.githubusercontent.com/7524875/127541475-5c05322a-f462-426d-978e-2496a52dfce4.jpg)

So i tested manually opening this port range and the backup job back to work.
![photo_2021-07-29_14-52-18](https://user-images.githubusercontent.com/7524875/127541574-143bea8c-079f-49dc-9bdd-ca5f558252a8.jpg)

So I'd like to suggest to possibly include this UFW rule in the script in order to open these ports required by data transfer.

Thanks.

**Comment by tdewin** [comment]
Hey,

I need to verify this because normally the system should open up the port automatically during backup. 

Can you post your vbr build number and Ubuntu unable -a output?

**Comment by eduzimrs** [comment]
Hi,

Veeam 11.0.0.837 Patch 20210525
I did not follow the Ubuntu unable -a? if it is the version Ubuntu 20.04.2 LTS

**Comment by eduzimrs** [comment]
Hi,

I trace the Veeam Logs, here's what i found:

Veeam Server's log:

29.07.2021 15:50:32] <32> Error        Failed to connect to the port [vlinuxxfs.plattanolabs.com.br:**2502**].
[29.07.2021 15:50:32] <32> Error        --tr:Failed to connect to target endpoint.
[29.07.2021 15:50:32] <32> Error        --tr:Client failed to process the command. Command: [connectByIPs].
[29.07.2021 15:50:32] <32> Error        --tr:event:1:
[29.07.2021 15:50:32] <32> Error        --tr:event:3:
[29.07.2021 15:50:32] <32> Error         (Veeam.Backup.Common.CAppException)
[29.07.2021 15:50:32] <32> Error           at Veeam.Backup.AgentProvider.CClientAgentProtocol.WaitUntilWorking(Int32 timeout)
[29.07.2021 15:50:32] <32> Error           at Veeam.Backup.AgentProvider.CClientAgentProtocol.ConnectByIPs(IEnumerable`1 addrs, String username, String pwd, Int32 addConnectionsCount, Guid sessionId)
[29.07.2021 15:50:32] <32> Error           at Veeam.Backup.AgentProvider.CBackupClient.Connect(CServerConnParams prms, Int32 addConnectionsCount, Guid sessionId)
[29.07.2021 15:50:32] <32> Error        --- End of stack trace from previous location where exception was thrown ---


Saying that couldn't connect to Linux at port 2502, but the Linux log file says that the port was opened:

[29.07.2021 15:50:26.736] <140394209728256> cli      | Firewall.Open
[29.07.2021 15:50:26.736] <140394209728256> cli      |   (EString) Id = Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.736] <140394209728256> cli      |   (EInt32) Port = 2502
[29.07.2021 15:50:26.736] <140394209728256> cli      | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[29.07.2021 15:50:26.737] <140279266064192> fir      |   [CFirewallController] Open 2502 port
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [ 2] 2506/tcp                   ALLOW IN    Anywhere                   # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [ 3] 2506/tcp                   ALLOW OUT   Anywhere                   (out) # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [ 4] 2500/tcp                   ALLOW IN    Anywhere                   # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [ 5] 2500/tcp                   ALLOW OUT   Anywhere                   (out) # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [ 6] 2501/tcp                   ALLOW IN    Anywhere                   # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [ 7] 2501/tcp                   ALLOW OUT   Anywhere                   (out) # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.824] <140279266064192> fir      |     '2502/tcp' is not found in rules table
[29.07.2021 15:50:26.824] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw allow in proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.825] <140279266064192>          |     Creating child process: ufw with arguments: allow, in, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.941] <140279266064192> fir      |     '2502/tcp' is not found in rules table
[29.07.2021 15:50:26.942] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw allow out proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:26.942] <140279266064192>          |     Creating child process: ufw with arguments: allow, out, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:27.062] <140279266064192> fir      |   [CFirewallController] Open 2502 port ok.
]

And right after the port 2502 is closed, looks like it is being closed before Veeam attempts to connect to it.

[29.07.2021 15:50:27.062] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule added
[29.07.2021 15:50:27.062] <140279266064192> fir      |   [CFirewallController] Open 2502 port ok.
**[29.07.2021 15:50:30.509] <140279266064192> fir      |   [CFirewallController] Close 2502 port
[29.07.2021 15:50:30.509] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw delete allow in proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:30.509] <140279266064192>          |     Creating child process: ufw with arguments: delete, allow, in, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:30.608] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule deleted
[29.07.2021 15:50:30.608] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw delete allow out proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:30.608] <140279266064192>          |     Creating child process: ufw with arguments: delete, allow, out, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:30.712] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule deleted
[29.07.2021 15:50:30.712] <140279266064192> fir      |   [CFirewallController] Close 2502 port ok.**
[29.07.2021 15:50:35.359] <140279266064192>          |   Change OOM for pid 10124 to 10 score
[29.07.2021 15:50:35.371] <140279266064192> fir      |   [CFirewallController] Check firewall availability
[29.07.2021 15:50:35.372] <140279266064192> fir      |   [CFirewallController] Check firewall availability ok.
[29.07.2021 15:50:35.373] <140279266064192> fir      |   [CFirewallController] Open 2502 port
[29.07.2021 15:50:35.373] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw status numbered
[29.07.2021 15:50:35.373] <140279266064192>          |     Creating child process: ufw with arguments: status, numbered
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Status: active
[29.07.2021 15:50:35.455] <140279266064192> fir      |
[29.07.2021 15:50:35.455] <140279266064192> fir      |          To                         Action      From
[29.07.2021 15:50:35.455] <140279266064192> fir      |          --                         ------      ----
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 1] 22/tcp                     ALLOW IN    Anywhere
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 2] 2506/tcp                   ALLOW IN    Anywhere                   # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 3] 2506/tcp                   ALLOW OUT   Anywhere                   (out) # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 4] 2500/tcp                   ALLOW IN    Anywhere                   # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 5] 2500/tcp                   ALLOW OUT   Anywhere                   (out) # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 6] 2501/tcp                   ALLOW IN    Anywhere                   # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 7] 2501/tcp                   ALLOW OUT   Anywhere                   (out) # Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [ 8] 22/tcp (v6)                ALLOW IN    Anywhere (v6)
[29.07.2021 15:50:35.455] <140279266064192> fir      |     Filter out firewall rules which is missing 'ALLOW IN' and contain 'v6'
[29.07.2021 15:50:35.455] <140279266064192> fir      |     '2502/tcp' is not found in rules table
[29.07.2021 15:50:35.455] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw allow in proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.455] <140279266064192>          |     Creating child process: ufw with arguments: allow, in, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.562] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule added
[29.07.2021 15:50:35.562] <140279266064192> fir      |     Filter out firewall rules which is missing 'ALLOW OUT' and contain 'v6'
[29.07.2021 15:50:35.562] <140279266064192> fir      |     '2502/tcp' is not found in rules table
[29.07.2021 15:50:35.562] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw allow out proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.562] <140279266064192>          |     Creating child process: ufw with arguments: allow, out, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.660] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule added
[29.07.2021 15:50:35.660] <140279266064192> fir      |   [CFirewallController] Open 2502 port ok.
[29.07.2021 15:50:35.806] <140279266064192> fir      |   [CFirewallController] Close 2502 port
[29.07.2021 15:50:35.806] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw delete allow in proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.806] <140279266064192>          |     Creating child process: ufw with arguments: delete, allow, in, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.903] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule deleted
[29.07.2021 15:50:35.903] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw delete allow out proto tcp to 0.0.0.0/0 port 2502 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:35.903] <140279266064192>          |     Creating child process: ufw with arguments: delete, allow, out, proto, tcp, to, 0.0.0.0/0, port, 2502, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:36.011] <140279266064192> fir      |     [CFirewallInvoker] Invoke result: 0 Rule deleted
[29.07.2021 15:50:36.011] <140279266064192> fir      |   [CFirewallController] Close 2502 port ok.
[29.07.2021 15:50:45.696] <140279266064192> fir      |   [CFirewallController] Close 2500 port
[29.07.2021 15:50:45.696] <140279266064192> fir      |     [CFirewallInvoker] Invoke: ufw delete allow in proto tcp to 0.0.0.0/0 port 2500 comment Veeam rule 0db6e258-7389-4012-a224-231a7842da77
[29.07.2021 15:50:45.696] <140279266064192>          |     Creating child process: ufw with arguments: delete, allow, in, proto, tcp, to, 0.0.0.0/0, port, 2500, comment, Veeam rule 0db6e258-7389-4012-a224-231a7842da77


Here the port is not opened:
![Screenshot 2021-07-29 160333](https://user-images.githubusercontent.com/7524875/127551030-5f88a041-49bd-4eb3-930a-aed840de94e5.png)

**Comment by tdewin** [comment]
For me, the system is automatically opening and closing (basically as you can see in the screenshots below). This is nothing I can really fix via this project. I would suggest to open a support ticket with Veeam Support and have them take a look although. It seems there is some mismatched in open ports. The rules you are showing are dynamic

During Backup:
![2021-07-30 12_47_44](https://user-images.githubusercontent.com/11536914/127642471-5252c739-88be-4fef-a6bd-447e97ad57b8.png)

After Backup:
![2021-07-30 12_48_12](https://user-images.githubusercontent.com/11536914/127642474-dfafaa79-95f0-4899-9dd6-ac7c2ef52b9c.png)

Test system, same VBR, update ubuntu to the latest soft (20.04.02).

**Comment by eduzimrs** [comment]
Ok, thanks I've opened a support case.
Appreciate.
